/*--------------------------------------------------------------------*/
/*  Copyright (2013) Sandia Corporation. Under the terms of Contract  */
/*  DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government    */
/*  retains certain rights in this software.                          */
/*                                                                    */
/*  For full terms of distribution see the accompanying LICENSE file. */
/*  To distribute this file outside of SESML, substitue the full text */
/*  of the LICENSE file for this notice.                              */
/*--------------------------------------------------------------------*/

#ifndef VARS_H
#define VARS_H

enum Vars {
  V_R = 0,
  V_V,
  V_T,
  V_P,
  V_G,
  V_F,
  V_H,
  V_E,
  V_S,
  V_CP,
  V_CV,
  V_CS,
  V_KT,
  V_G2P,
  V_M,
  V_L,
  V_MAX
};

#endif
